table Allocations
	lineageTag: b088863a-d908-4755-b685-9ce5f98e5497

	column AllocationID
		dataType: string
		isHidden
		lineageTag: 4c54fb5a-7f79-4f98-8a65-7dc527888f74
		summarizeBy: none
		sourceColumn: AllocationID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column InvoiceID
		dataType: string
		isHidden
		lineageTag: 3f0e52f1-4ebd-4387-833e-90c94c5fdc5d
		summarizeBy: none
		sourceColumn: InvoiceID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CustomerID
		dataType: string
		isHidden
		lineageTag: d04e50af-611f-48d8-a4f7-728bb72b376f
		summarizeBy: none
		sourceColumn: CustomerID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AllocationDate
		dataType: dateTime
		formatString: dd MMM yyyy
		lineageTag: 9b407798-b066-4bc4-8ed4-2e4659c9c938
		summarizeBy: none
		sourceColumn: AllocationDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column Amount
		dataType: decimal
		formatString: £#,##0
		lineageTag: 21b533cf-15c9-45eb-a465-17032435e03b
		summarizeBy: sum
		sourceColumn: Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	partition Allocations = m
		mode: import
		source =
				let
				    Source = Csv.Document(
				        Web.Contents(BaseUrl, [RelativePath = "allocations.csv"]),
				        [Delimiter = ",", Columns = 5, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]
				    ),
				    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(
				        PromotedHeaders,
				        {
				            {"AllocationID", type text},
				            {"InvoiceID", type text},
				            {"CustomerID", type text},
				            {"AllocationDate", type date},
				            {"Amount", Currency.Type}
				        },
				        "en-GB"
				    )
				in
				    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

